import some_message_pb2  # generated by protoc some_message.proto --output_py==.

msg = some_message_pb2.SomeMessage()
msg.first = 100
msg.second = "abcd"
msg.third.extend(["foo", "bar"])
msg.fourth = True
msg.fifth.value = -666
msg.fifth.text = "negative 666"
msg.sixth.extend([msg.NestedMessage(value=1234, text="onetwothreefour"),
                  msg.NestedMessage(value=2222, text="four twos")])
msg.seventh.extend([1,2,3,4])

print(msg)
print([i for i in msg.SerializeToString()])
with open("some_message.wire", "wb") as wire:
    wire.write(msg.SerializeToString())
